### ISSUE TITLE
dep: investigate lofty 0.24 compile failure (std::io::Take::seek)

### ISSUE THREAD

**Issue by forkwright** [forkwright/harmonia#292]
lofty 0.24.0 fails to compile with Rust 1.85 (our MSRV):

```
error[E0599]: no method named `seek` found for struct `std::io::Take`
  --> lofty-0.24.0/src/iff/chunk.rs:298:25
```

This is in lofty's own source code — not harmonia code. This appears to be either:
1. A lofty bug (std::io::Take gained Seek only in later Rust versions)
2. An MSRV bump in lofty 0.24 that we have not accommodated

Investigation needed:
- Check lofty 0.24 release notes / MSRV requirements
- If MSRV bump: evaluate whether to bump harmonia MSRV or hold at lofty 0.22.4
- If lofty bug: check if 0.24.x patch release fixes it

See PR #285.
